adminUser:
  password: vault:beet/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: cesarac66@hotmail.com
  token: vault:beet/pipelineUser:token
  username: AdrianVarelaG
prow:
  hmacToken: vault:beet/prow:hmacToken
